apiVersion: api.github.com/v1
kind: Autoscaler
metadata:
  labels:
    app.kubernetes.io/name: autoscaler
    app.kubernetes.io/instance: autoscaler-sample
    app.kubernetes.io/part-of: custom-autoscaler2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: custom-autoscaler2
  name: autoscaler-sample
spec:
  # TODO(user): Add fields here
